name = "backend"
compatibility_date = "2023-01-01"
routes = [
	{ pattern = "api.tape.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
LOGTAIL_API_KEY=""
EVER_ACCESS_KEY=""
EVER_ACCESS_SECRET=""

[[d1_databases]]
binding = "DB"
database_name = "my-database"
database_id = ""

